# Generated by Django 4.1 on 2022-09-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedtraits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='question',
            field=models.TextField(default=''),
        ),
    ]
