# Generated by Django 4.1 on 2022-08-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedtraits', '0002_questionmodel_useranswermodel_delete_sharedtraits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswermodel',
            name='question',
        ),
        migrations.AddField(
            model_name='useranswermodel',
            name='questionID',
            field=models.IntegerField(default=-1),
        ),
    ]
